import codecs
import json
import re

html = codecs.open('c:/Users/SB/Desktop/연습용/pre9807_data.html', 'r', 'utf-8').read()

parts = []

# Find all <tr> in tbody
tbody = re.search(r'<tbody>(.*?)</tbody>', html, re.DOTALL).group(1)
trs = re.findall(r'<tr>(.*?)</tr>', tbody, re.DOTALL)

for i, tr in enumerate(trs):
    # Category name
    cat_match = re.search(r'<strong>(.*?)</strong>', tr)
    if not cat_match: continue
    cat_name = cat_match.group(1).strip()
    
    # Items
    td = re.search(r'<td>(.*?)</td>', tr, re.DOTALL).group(1)
    items_matches = re.findall(r'<li><span>(\d+\))</span>(.*?)</li>', td)
    
    # Rates
    th = re.search(r'<th>(.*?)</th>', tr, re.DOTALL).group(1)
    # The first <li> is usually empty / placeholder for the category title
    rate_lis = re.findall(r'<li>(.*?)</li>', th)
    # Clean rates
    rates = []
    for r in rate_lis:
        clean_r = r.strip()
        if clean_r == '　' or clean_r == '': continue
        rates.append(clean_r)
    
    cat_items = []
    for j, (num, desc) in enumerate(items_matches):
        if j < len(rates):
            rate_val = rates[j] + "%"
        else:
            rate_val = "-"
            
        desc = desc.strip()
        desc = re.sub(r'<[^>]+>', '', desc)
        
        cat_items.append({
            "desc": f"{num} {desc}",
            "rate": rate_val
        })
        
    parts.append({
        "category": f"{i+1}. {cat_name}",
        "items": cat_items,
        "expIndices": []
    })

parts_json_str = json.dumps(parts, ensure_ascii=False, indent=12)
parts_json_str = parts_json_str.replace('\n            {', ' {').replace('\n            }', ' }')

# Prepare new vPre9807_nonlife block
new_vPre9807 = f'''"vPre9807_nonlife": {{
        type: "parts_only",
        parts: {parts_json_str},
        explanations: []
    }},'''

script_text = codecs.open('c:/Users/SB/Desktop/연습용/script.js', 'r', 'utf-8').read()

# Replace the specific dummy line
dummy_line = '"vPre9807_nonlife": [{ category: "복구 중", items: [{ desc: "데이터가 유실되어 복구 중입니다.", rate: "-" }] }],'
if dummy_line in script_text:
    script_text = script_text.replace(dummy_line, new_vPre9807)
else:
    # If it's already an object (maybe generated by reconstruct), replace it
    v_start = script_text.find('"vPre9807_nonlife": {')
    if v_start != -1:
        # find end
        brace_count = 0
        in_obj = False
        v_end = -1
        for j in range(v_start + len('"vPre9807_nonlife": '), len(script_text)):
            if script_text[j] == '{':
                brace_count += 1
                in_obj = True
            elif script_text[j] == '}':
                brace_count -= 1
                if in_obj and brace_count == 0:
                    v_end = j
                    break
        if v_end != -1:
            # Check for trailing comma
            if script_text[v_end+1] == ',':
                v_end += 1
            script_text = script_text[:v_start] + new_vPre9807 + script_text[v_end+1:]
    else:
        print("COULD NOT FIND target to replace!")

codecs.open('c:/Users/SB/Desktop/연습용/script.js', 'w', 'utf-8').write(script_text)
print("Updated script.js with vPre9807_nonlife data!")
