import json
import base64
import codecs
import re

def get_b64_img(path, caption):
    try:
        with open(path, "rb") as f:
            b = base64.b64encode(f.read()).decode("utf-8")
        
        # Adding caption, making it smaller, clickable
        html = f'''
        <div style="text-align:center; margin:15px; display:inline-block; vertical-align:top;">
            <img src="data:image/png;base64,{b}" class="doc-image" style="max-width:350px; cursor:pointer; border:1px solid #ddd; padding:5px; background:#fff; border-radius:4px;" onclick="showImageModal(this.src)">
            <div style="margin-top:10px; font-weight:bold; font-size:15px; letter-spacing:1px;">&lt; {caption} &gt;</div>
        </div>
        '''
        return html
    except:
        return ''

chest_img = get_b64_img('c:/Users/SB/Desktop/연습용/가슴뼈.png', '가슴뼈')
pelvis_img = get_b64_img('c:/Users/SB/Desktop/연습용/골반뼈.png', '골반뼈')
toe_img = get_b64_img('c:/Users/SB/Desktop/연습용/발가락.png', '발가락')
finger_img = get_b64_img('c:/Users/SB/Desktop/연습용/손가락.png', '손가락')

# Reload from the clean base generated by docx parser without injected media at the end
data = json.load(codecs.open('c:/Users/SB/Desktop/연습용/latest_data_media.json', 'r', 'utf-8'))

# Clean previously added HTML if I am running this on an already modified file
# Wait, latest_data_media.json doesn't have the manually appended images at the end! 
# (Only parse_latest_with_media.py generated it, and it only had the docx embedded images, wait. The docx didn't have these 4 images, they were missing!)
# So latest_data_media.json is clean of these 4 images.

# 1. Insert Images
for p in data['explanations']:
    if '7. 체간골의 장해' in p['title']:
        p['content'] += f"<br><div style='text-align:center;'>{chest_img}{pelvis_img}</div>"
    elif '10. 손가락의 장해' in p['title']:
        p['content'] += f"<br><div style='text-align:center;'>{finger_img}</div>"
    elif '11. 발가락의 장해' in p['title']:
        p['content'] += f"<br><div style='text-align:center;'>{toe_img}</div>"
        
    # 3. Center align '항목' and '점수' in 귀의 장해 table
    if '2. 귀의 장해' in p['title']:
        # The table has <td ...>항목</td> and <td ...>점수</td>
        # We can just replace those specific <td>s to have text-align:center
        p['content'] = re.sub(r'(<td[^>]*>)(항목|점수|내 용|검사|소견)(</td>)', r'\1<div style="text-align:center; font-weight:bold;">\2</div>\3', p['content'])

# 2. ADL Table HTML
adl_html = """
<table class="doc-table adls-table" style="width:100%; border-collapse: collapse; margin-top:20px; font-size:14px; border:1px solid #ccc; text-align:center;">
    <thead>
        <tr style="background-color:#f5f5f5; font-weight:bold;">
            <td style="border: 1px solid #ccc; padding: 10px; width:15%;">유형</td>
            <td style="border: 1px solid #ccc; padding: 10px; width:75%;">제한 정도</td>
            <td style="border: 1px solid #ccc; padding: 10px; width:10%;">지급률</td>
        </tr>
    </thead>
    <tbody>
        <!-- 이동동작 -->
        <tr>
            <td rowspan="4" style="border: 1px solid #ccc; padding: 8px; font-weight:bold; background-color:#fafafa;">이동동작</td>
            <td style="border: 1px solid #ccc; padding: 8px; text-align:left;">- 특별한 보조기구를 사용함에도 불구하고 다른 사람의 계속적인 도움이 없이는 방 밖을 나올 수 없는 상태 또는 침대에서 휠체어로 옮기기를 포함하여 휠체어 이동시 다른 사람의 계속적인 도움이 필요한 상태</td>
            <td style="border: 1px solid #ccc; padding: 8px;">40%</td>
        </tr>
        <tr>
            <td style="border: 1px solid #ccc; padding: 8px; text-align:left;">- 휠체어 또는 다른 사람의 도움 없이는 방밖을 나올 수 없는 상태 또는 보행이 불가능하나 스스로 휠체어를 밀어 이동이 가능한 상태</td>
            <td style="border: 1px solid #ccc; padding: 8px;">30%</td>
        </tr>
        <tr>
            <td style="border: 1px solid #ccc; padding: 8px; text-align:left;">- 목발 또는 보행기(walker)를 사용하지 않으면 독립적인 보행이 불가능한 상태</td>
            <td style="border: 1px solid #ccc; padding: 8px;">20%</td>
        </tr>
        <tr>
            <td style="border: 1px solid #ccc; padding: 8px; text-align:left;">- 보조기구 없이 독립적인 보행은 가능하나 보행시 파행(절뚝거림)이 있으며, 난간을 잡지 않고는 계단을 오르내리기가 불가능한 상태 또는 평지에서 100m 이상을 걷지 못하는 상태</td>
            <td style="border: 1px solid #ccc; padding: 8px;">10%</td>
        </tr>
        <!-- 음식물 섭취 -->
        <tr>
            <td rowspan="4" style="border: 1px solid #ccc; padding: 8px; font-weight:bold; background-color:#fafafa;">음식물 섭취</td>
            <td style="border: 1px solid #ccc; padding: 8px; text-align:left;">- 입으로 식사를 전혀 할 수 없어 계속적으로 튜브(비위관 또는 위루관)나 경정맥 수액을 통해 부분 혹은 전적인 영양공급을 받는 상태</td>
            <td style="border: 1px solid #ccc; padding: 8px;">20%</td>
        </tr>
        <tr>
            <td style="border: 1px solid #ccc; padding: 8px; text-align:left;">- 수저 사용이 불가능하여 다른 사람의 계속적인 도움이 없이는 식사를 전혀 할 수 없는 상태</td>
            <td style="border: 1px solid #ccc; padding: 8px;">15%</td>
        </tr>
        <tr>
            <td style="border: 1px solid #ccc; padding: 8px; text-align:left;">- 숟가락 사용은 가능하나 젓가락 사용이 불가능하여 음식물 섭취에 있어 부분적으로 다른 사람의 도움이 필요한 상태</td>
            <td style="border: 1px solid #ccc; padding: 8px;">10%</td>
        </tr>
        <tr>
            <td style="border: 1px solid #ccc; padding: 8px; text-align:left;">- 독립적인 음식물 섭취는 가능하나 젓가락을 이용하여 생선을 바르거나 음식물을 자르지는 못하는 상태</td>
            <td style="border: 1px solid #ccc; padding: 8px;">5%</td>
        </tr>
        <!-- 배변·배뇨 -->
        <tr>
            <td rowspan="4" style="border: 1px solid #ccc; padding: 8px; font-weight:bold; background-color:#fafafa;">배변·배뇨</td>
            <td style="border: 1px solid #ccc; padding: 8px; text-align:left;">- 배설을 돕기 위해 설치한 의료장치나 외과적 시술물을 사용함에 있어 타인의 계속적인 도움이 필요한 상태, 또는 지속적인 유치도뇨관 삽입상태, 방광루, 요도루, 장루상태</td>
            <td style="border: 1px solid #ccc; padding: 8px;">20%</td>
        </tr>
        <tr>
            <td style="border: 1px solid #ccc; padding: 8px; text-align:left;">- 화장실에 가서 변기위에 앉는 일(요강을 사용하는 일 포함)과 대소변 후에 뒤처리시 다른 사람의 계속적인 도움이 필요한 상태, 또는 간헐적으로 자가 인공도뇨가 가능한 상태(CIC), 기저귀를 이용한 배뇨, 배변 상태</td>
            <td style="border: 1px solid #ccc; padding: 8px;">15%</td>
        </tr>
        <tr>
            <td style="border: 1px solid #ccc; padding: 8px; text-align:left;">- 화장실에 가는 일, 배변, 배뇨는 독립적으로 가능하나 대소변후 뒤처리에 있어 다른 사람의 도움이 필요한 상태</td>
            <td style="border: 1px solid #ccc; padding: 8px;">10%</td>
        </tr>
        <tr>
            <td style="border: 1px solid #ccc; padding: 8px; text-align:left;">- 빈번하고 불규칙한 배변으로 인해 2시간 이상 계속되는 업무를 수행하는 것이 어려운 상태, 또는 배변, 배뇨는 독립적으로 가능하나 요실금, 변실금이 있는 때</td>
            <td style="border: 1px solid #ccc; padding: 8px;">5%</td>
        </tr>
        <!-- 목욕 -->
        <tr>
            <td rowspan="3" style="border: 1px solid #ccc; padding: 8px; font-weight:bold; background-color:#fafafa;">목욕</td>
            <td style="border: 1px solid #ccc; padding: 8px; text-align:left;">- 세안, 양치, 샤워, 목욕 등 모든 개인위생 관리시 타인의 지속적인 도움이 필요한 상태</td>
            <td style="border: 1px solid #ccc; padding: 8px;">10%</td>
        </tr>
        <tr>
            <td style="border: 1px solid #ccc; padding: 8px; text-align:left;">- 세안, 양치시 부분적인 도움 하에 혼자서 가능하나 목욕이나 샤워시 타인의 도움이 필요한 상태</td>
            <td style="border: 1px solid #ccc; padding: 8px;">5%</td>
        </tr>
        <tr>
            <td style="border: 1px solid #ccc; padding: 8px; text-align:left;">- 세안, 양치와 같은 개인위생관리를 독립적으로 시행가능하나 목욕이나 샤워시 부분적으로 타인의 도움이 필요한 상태</td>
            <td style="border: 1px solid #ccc; padding: 8px;">3%</td>
        </tr>
        <!-- 옷 입고 벗기 -->
        <tr>
            <td rowspan="3" style="border: 1px solid #ccc; padding: 8px; font-weight:bold; background-color:#fafafa;">옷 입고 벗기</td>
            <td style="border: 1px solid #ccc; padding: 8px; text-align:left;">- 상·하의 의복 착탈시 다른 사람의 계속적인 도움이 필요한 상태</td>
            <td style="border: 1px solid #ccc; padding: 8px;">10%</td>
        </tr>
        <tr>
            <td style="border: 1px solid #ccc; padding: 8px; text-align:left;">- 상·하의 의복 착탈시 부분적으로 다른 사람의 도움이 필요한 상태 또는 상의 또는 하의중 하나만 혼자서 착탈의가 가능한 상태</td>
            <td style="border: 1px solid #ccc; padding: 8px;">5%</td>
        </tr>
        <tr>
            <td style="border: 1px solid #ccc; padding: 8px; text-align:left;">- 상·하의 의복착탈시 혼자서 가능하나 미세동작(단추 잠그고 풀기, 지퍼 올리고 내리기, 끈 묶고 풀기 등)이 필요한 마무리는 타인의 도움이 필요한 상태</td>
            <td style="border: 1px solid #ccc; padding: 8px;">3%</td>
        </tr>
    </tbody>
</table>
"""

for p in data['explanations']:
    if 'ADLs' in p['title']:
        p['content'] = adl_html

# 3. Add link to 13 - 1) Using jumpToExp('exp-14') which is the ID of ADLs explanation in v1804
# Wait, is ADLs exp-14? Let's verify index dynamically:
adl_idx = next(i for i, e in enumerate(data['explanations']) if 'ADLs' in e['title'])
target_exp_id = f"exp-{adl_idx}"

for part in data['parts']:
    if '13.' in part['category'] and '신경계' in part['category']:
        for item in part['items']:
            if '일상생활 기본동작' in item['desc']:
                item['desc'] = item['desc'].replace(
                    '일상생활 기본동작', 
                    f'<a href="#" class="adl-jump-link" style="color:#0056b3; text-decoration:underline; font-weight:bold;" onclick="event.preventDefault(); jumpToExp(\'{target_exp_id}\'); return false;">일상생활 기본동작</a>'
                )

# Save back to latest_data_media3.json
with codecs.open('c:/Users/SB/Desktop/연습용/latest_data_media3.json', 'w', 'utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)
    
print(f"Images resized/captioned, 귀 table centered, link fixed to jumpToExp('{target_exp_id}').")
