import codecs
import json
import re

# Load 9502 grades
script = codecs.open('c:/Users/SB/Desktop/연습용/script.js', 'r', 'utf-8').read()
idx1 = script.find('v9502_life_9901')
g_start = script.find('grades: [', idx1)
g_end = script.find('parts: [', g_start)

# To parse grades properly with regex since it's JS (not strict JSON if keys are unquoted, though my script output strict JSON for grades)
grades_text = script[g_start+8:g_end].strip()
if grades_text.endswith(','): grades_text = grades_text[:-1]
grades_9502 = json.loads(grades_text) # This works because grades was generated by json.dumps!

map_9502 = {}
for g in grades_9502:
    for item in g['items']:
        clean = re.sub(r'^\d+\.\s*', '', item['desc']).strip()
        clean = re.sub(r'<[^>]+>', '', clean).strip()
        rate = f"{g['category'][-2:]}{item['desc'].split('.')[0]}항"
        map_9502[clean] = rate
        map_9502[clean.replace(' ', '')] = rate

# 9902 parts
v9902_idx = script.find('"v9902_life": {')
p_start = script.find('parts: [', v9902_idx)
p_end = script.find('explanations: [', p_start)
parts_text = script[p_start+7:p_end].strip()

categories = re.findall(r'\{\s*category:\s*"([^"]+)",\s*items:\s*\[(.*?)\](?:,\s*expIndices:\s*\[([\d,\s]*)\])?\s*\}', parts_text, re.DOTALL)

new_parts_data = []

for cat, items_str, exp_str in categories:
    print(f"\n[{cat}]")
    cat_items = []
    item_matches = re.findall(r'\{\s*desc:\s*"([^"]+)",\s*rate:\s*"([^"]+)"\s*\}', items_str)
    
    for desc, rate in item_matches:
        clean = re.sub(r'^\d+\.\s*', '', desc).strip()
        clean = re.sub(r'<[^>]+>', '', clean).strip()
        clean_ns = clean.replace(' ', '')
        
        if clean in map_9502:
            print(f"  EXACT: {desc} -> {map_9502[clean]}")
            cat_items.append({"desc": desc, "rate": map_9502[clean]})
        elif clean_ns in map_9502:
            print(f"  NO-SPACE: {desc} -> {map_9502[clean_ns]}")
            cat_items.append({"desc": desc, "rate": map_9502[clean_ns]})
        else:
            print(f"  MISSING (deleting): {desc}")
            
    if cat_items:
        exp_indices = [int(x.strip()) for x in exp_str.split(',')] if exp_str.strip() else []
        new_parts_data.append({"category": cat, "items": cat_items, "expIndices": exp_indices})

# Output new parts data for 9502
parts_json_str = json.dumps(new_parts_data, ensure_ascii=False, indent=12)
parts_json_str = parts_json_str.replace('\n            {', ' {').replace('\n            }', ' }')

# Update script.js for 9502
script = script[:script.find('parts: [', idx1)] + "parts: " + parts_json_str + ",\n        " + script[script.find('explanations: [', idx1):]
codecs.open('c:/Users/SB/Desktop/연습용/script.js', 'w', 'utf-8').write(script)
print("\nUpdated script.js! Removed missing items.")
